### ISSUE TITLE
Fill bucket problems

### ISSUE THREAD

**Issue by kateliev** [kateliev/TypeRig#14]
It seems that Fill bucket tool is actually a dynamic filter that messes up proper node indexing manipulation and etc. Investigate a solution!

**Comment by tphinney** [comment]
Yes, using the Fill tool turns on a "fill" filter that enables what I call "fancy fill effects." Using scissors tool can also trigger a fill filter.

In a single-master font, this can be nice. But it is not compatible with variations.

To manually turn off the filter, do Element > Remove Filter.

**Comment by twardoch** [comment]
Fill is compatible with variations as long as the dynamically flattened results match. When you use fill, the dynamically flattened results have overlaps removed — so if you use Fill in one master but you don’t use Fill in another (but you have overlaps there), then they don’t match. But if you use Fill well in all masters, the results match. In FLVI, with any filter (like smart corners, Fill, Glue), master matching and interpolation are done **after** flattening, i.e. on the final outlines.

**Comment by tphinney** [comment]
OK, so the filter is compatible with variations IF it is used in all masters, AND the results are compatible in all masters. But in many cases, if the results _were_ compatible in all masters, I probably wouldn't have needed the fill in the first place.

Does the compatibility flag check for this issue?

**Comment by twardoch** [comment]
You don't need to use the filter in all masters. It just matters that the final contours match. 

If a filter is used, the final contours are the flattened outlines (with overlaps removed). 

If no filter is used, then it's just the normal contours you see. If those contours have overlaps, then the masters won't match because the master with a filter has (from the matching pov) no overlaps while the master that has no filter has overlaps.

If there is a filter, the contours for matching are obtained dynamically and there is no guarantee that the sequence of contours or nodes match with a simple layer, since you don't have control over the order of the final contours and nodes in a layer that uses a filter. 

In that case, turning one or both options in Font Info > Variations may help to get from red (no match) to yellow (loose match i.e. those options are resorting stuff to make the match).

It's hard to tell anything more with setting a specific example.
