### ISSUE TITLE
Smart Corners

### ISSUE THREAD

**Issue by insignedesign** [kateliev/TypeRig#16]
I'm having difficulty with the smart corners.  I click Apply Smart Corner but I get:

ERROR:	 Please specify a Glyph with suitable Shape Builder (Smart corner) first!
Traceback (most recent call last):
  File "C:/TypeRig-master/Scripts/TypeRig GUI\Filter\Corner.py", line 106, in <lambda>
    self.btn_apply_smartCorner.clicked.connect(lambda: self.apply_SmartCorner(False))
  File "C:/TypeRig-master/Scripts/TypeRig GUI\Filter\Corner.py", line 377, in apply_SmartCorner
    active_preset = self.getPreset()
  File "C:/TypeRig-master/Scripts/TypeRig GUI\Filter\Corner.py", line 210, in getPreset
    active_preset_index = self.tab_presets.selectionModel().selectedIndexes[0].row()
IndexError: tuple index out of range
DONE:	 Update/Snapshot for glyphs: _469

I prepared a short video here: https://www.twitch.tv/videos/453177892

**Comment by kateliev** [comment]
**In short:** 
Currently the API does not give us a way to create Smart Corner from scratch, so we have to clone it from somewhere. In order to do that, you need to: 

- create at least one Smart Corner on glyph of your choosing; parameters (radius) of that newly created corner are of no importance.
- get the name of that glyph and write/paste it in the "Builder" filed under "Smart Corner" in "Filter Panel"... or just select that glyph with Smart corner in "Font panel"... and then press "Set Builder" button. 

That is all. From here on you can create as many Smart Corners as you wish with custom parameters of your choosing as long as the "Builder" (ShapeBuilder) is properly set.

**Comment by insignedesign** [comment]
I believe I have followed your instructions properly, but I am getting this error: 

Traceback (most recent call last):
  File "C:/TypeRig-master/Scripts/TypeRig GUI\Filter\Corner.py", line 106, in <lambda>
    self.btn_apply_smartCorner.clicked.connect(lambda: self.apply_SmartCorner(False))
  File "C:/TypeRig-master/Scripts/TypeRig GUI\Filter\Corner.py", line 377, in apply_SmartCorner
    active_preset = self.getPreset()
  File "C:/TypeRig-master/Scripts/TypeRig GUI\Filter\Corner.py", line 210, in getPreset
    active_preset_index = self.tab_presets.selectionModel().selectedIndexes[0].row()
IndexError: tuple index out of range

![image](https://user-images.githubusercontent.com/9338935/61837787-4c2cc880-ae54-11e9-8c3c-ddbc065906d3.png)

**Comment by kateliev** [comment]
Did you try entering smart corner radius in the appropriate preset filed. For it to work, you have to give the radius for each master as a preset, select that preset and execute the command from then on, the filter panel will remember your last choice and will apply the corner, until you select another preset. 

**The given error**  indicates that no preset was selected. Also as I see you have both radii set to 0.

**Comment by insignedesign** [comment]
Fantastic, it works. this is a definite improvement. Any word on when this could do both masters at the same time (instead of having to switch to the layer and click the button again)? Or, do I have something mis-configured?
