### ISSUE TITLE
[wish] TR Letterspacer

### ISSUE THREAD

**Issue by twardoch** [kateliev/TypeRig#41]
Huerta Typografica created the HT Letterspacer, which works as a Glyphs plugin. It seems quite decent.

- http://letterspacer.huertatipografica.com/
- https://github.com/huertatipografica/HTLetterspacer

Unfortunately, they merged everything into one file, UI, the "engine" etc. Also, their code is GPL3. 

If we were to adapt this to FontLab, this means: 

1. Create a separate `TypeRigLetterspacerLib` (or so) Github repo which will hold code adapted taken from their code. Basically, it should be a Python package.
2. In the TypeRig repo, only add FL/TR-unique code, recreated conceptually from the HT Letterspacer GUI.

**Comment by kateliev** [comment]
@twardoch - now we have this - **typerig.proxy.sampler** module. It could essentially do the same, but is an engine for finding _negative (+mixed) space_ area and all sort of other analysis with that info.  Conceptually it resembles _HT Letterspacer,_ but in fact i ended writing up my own code, so we would not need all that GPL3 stuff. Nevertheless i mention the source of inspiration it in the code...

So try the following - open any font and any glyph and run:

```
import fontlab as fl6
import fontgate as fgt
from typerig.proxy import *

# - Init
f = pFont()
g = eGlyph()

# - Config
ascender = f.fontMetrics().getAscender()
descender = f.fontMetrics().getDescender()
 
# -- Window of sampling: we only specify the Y direction as X is based on glyph BBox
sampling_window = (descender, ascender)
# -- Frequency (step) of sampling
sampling_frequency = 20

# - Create the sampler
s = GlyphSampler(sampling_window, sampling_frequency)

# Get area of: left, mid*, right space, where lef anf rigth represent the whitespace while mid is mixed black (outline) and white (within it)
area = s.sampleGlyphArea(g)
print area

# ... also meseurments are cached so that
print s.data_area[g.name]
# would return the same. 

# ...and finally the following 
s.drawGlyphArea(g)
g.updateObject(g.fl)
# would draw the area/samples on a special mask layer
```

It is all written with scalability and modular usage in mind. There are a bunch of @staticmethod functions that represent the core and could be used in any way one sees fit. The code is reasonably fast. It could be made faster if i get rid of the modular tools idea and make it within one or two loops.... but i think that is fast enough and more usable. Also all data is cached so that it could be reused, where _.data_area_ caches the calculated area and _.data_sapmples_ stores the original sampling data.

Now the major issue. The code never really fulfills the task given - yes it will give you the areas, but will not return sidebearing values for metrics as HT Letterspacer does. This is perhaps because my own implementation is a bit different, but manly because i did not understand the the calculations they make with the area for receiving the desired SB values - for me their math just does not make any sense...

So what could we use it for:
- negative to positive space evaluation (especially if you remove the glyph outline area from the mid-mixed area);
- auto metrics generation like HT Letterspacer - with some other formula (or the original one) so if you have one or idea just post it here; 
- auto metrics linking - that is why i keep the cached data in the object so that we could evaluate how the metrics of the current glyph differ: a) among themselves - left to right and etc; b) compared to other glyphs /H, /O, /n, /o and etc.

.... and the crown jewel:
we could use this as bubble kern engine, neural net kerning and etc....

**Comment by kateliev** [comment]
The basic tool is now done **Metrics-Panel > Auto Metrics**. _It works as usual in accordance to TR Masthead (multiple glyphs and layers)._ 

It uses my own way to calculate negative to positive space ratio and etc. stuff needed for seedbearing calculation, but with mixed results... I cannot really say I am happy about it, but at least the way it works is transparent and logical. _The calculated results differ from HT's +/- 2(3) units which I think is not a big deal after all..._

It needs a lot of refinement though... just as the original HT Letterspacer it needs a table of positive to negative area values to cover all glyph cases, exceptions and etc. That is why there will be an _Advanced options section_ developed in some unforeseen future... for now I am closing this...
