### ISSUE TITLE
Selecting Panel gives error code

### ISSUE THREAD

**Issue by bodonibdoy** [kateliev/TypeRig#45]
Using FL7 7.1.4.7515. Others load fine.
Error:
Traceback (most recent call last):
  File "/Users/georgethompson/Library/Application Support/FontLab/FontLab 7/Scripts/TypeRig GUI/typerig-panel.py", line 23, in <module>
    import Panel 
  File "/Users/georgethompson/Library/Application Support/FontLab/FontLab 7/Scripts/TypeRig GUI/Panel/__init__.py", line 19, in <module>
    __import__(module, locals(), globals())
  File "/Users/georgethompson/Library/Application Support/FontLab/FontLab 7/Scripts/TypeRig GUI/Panel/TextBock.py", line 14, in <module>
    from typerig import QtGui
ImportError: cannot import name QtGui

George

**Comment by kateliev** [comment]
Hi George, to be honest i believe you are using a TR version that is way too old. I cannot really tell what is wrong with it besides the fact the TextBlock panel gives an import error. This panel has been moved to a new location/folder at least 5 months ago (this is how i can tell you are using an old copy of TR). There are two ways of fixing this:

- Update/download the latest version of TR and overwrite your old one;
_... this might be not such a good idea unless you update your FL to more recent version, because some PyApi stuff has been added and TR changed also. I am using build 7585 and it is "ancient" already_

- Disable the sub-panel from loading, by adding underscore to the file name: `TextBock.py` will become `_TextBock.py` 
_... this is a reasonable solution if you feeling well with your current FL+TR installation_

_PS: Have in mind that TypeRig is updated daily, so best practice is to get a new version every week, or at least monthly..._

**Comment by bodonibdoy** [comment]
Thanks, new version did the trick.

> On Oct 28, 2020, at 2:24 AM, Vassil Kateliev <notifications@github.com> wrote:
> 
> 
> Hi George, to be honest i believe you are using a TR version that is way too old. I cannot really tell what is wrong with it besides the fact the TextBlock panel gives an import error. This panel has been moved to a new location/folder at least 5 months ago (this is how i can tell you are using an old copy of TR). There are two ways of fixing this:
> 
> 	• Update/download the latest version of TR and overwrite your old one;
> ... this might be not such a good idea unless you update your FL to more recent version, because some PyApi stuff has been added and TR changed also. I am using build 7585 and it is "ancient" already
> 
> 	• Disable the sub-panel from loading, by adding underscore to the file name: TextBock.py will become _TextBock.py
> ... this is a reasonable solution if you feeling well with your current FL+TR installation
> 
> PS: Have in mind that TypeRig is updated daily, so best practice is to get a new version every week, or at least monthly...
> 


Regards,
George
-----
George E. Thompson
No Bodoni Typography
gthompson@nobodoni.com
nobodoni.com
georgeverethompson.com

"I felt bad because I had no shoes, until I met a man who had no Bodoni."

**Comment by bodonibdoy** [comment]
Everytime I try to use the Anchors in the GUI I get an error message (below), regardless of typeface or glyph. Using TR Nov 25.

 Traceback (most recent call last):
  File "/Users/georgethompson/Library/Application Support/FontLab/FontLab 7/Scripts/TypeRig GUI/Panel/Anchor.py", line 157, in refresh
    self.data = [((layer.name), [(anchor.name, int(anchor.point.x()), int(anchor.point.y()), anchor.expressionX, anchor.expressionY) for anchor in self.glyph.anchors(layer.name)]) for layer in self.glyph.masters()]
AttributeError: 'flObject' object has no attribute 'point'



Regards,
George
-----
George E. Thompson
No Bodoni Typography
gthompson@nobodoni.com
nobodoni.com
georgeverethompson.com

"I felt bad because I had no shoes, until I met a man who had no Bodoni."

**Comment by kateliev** [comment]
Hi, It seems you are using a TR version that is rather recent and looking at the code (line 157) it matches exactly what i have at my side and... it works! 

So my question is what version/build is your FontLab 7 and is it on Mac or Win. I am running 7.2.0.7622 and can confirm that everything is working.

_"AttributeError: 'flObject' object has no attribute 'point'"_
I am asking because these kind of errors occur with bad FL builds,  where a specific API object like the Anchor object (called **flPinPoint** ) is turned into generic object **flObject** .
